config/routes.rb
Rails.application.routes.draw do
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
#   get 'lists/new' #'lists'コントローラーの'new'アクションを呼び出す
  get 'top' => 'homes#top' #GETリクエストが `/top` というパスに対して送信された場合に、`homes`コントローラーの`top`アクションを呼び出す
  resources :lists
  
#   post 'lists' => 'lists#create' #lists_controller.rb 内変数 create 新しいデータの作成
#   get 'lists' => 'lists#index'  #'lists'コントローラーの'index'アクションを呼び出す
  
  #どの投稿データを表示するかを判別するために、投稿データのidもURLに含めます。 
  #たとえば、URLが/lists/1の場合、params[:id] と記述すると、id=1を取り出せます。
#   get 'lists/:id' => 'lists#show', as: 'list'#getリクエストがlists/:idというパスに送信された場合'lists'コントローラーの'show'アクションを呼び出す
  
#   get 'lists/:id/edit' => 'lists#edit', as: 'edit_list'#getリクエストがlists/:idというパスに送信された場合'lists'コントローラーの'edit'アクションを呼び出す

#   patch 'lists/:id' => 'lists#update', as: 'update_list'#patchリクエストがlists/:idというパスに送信された場合'lists'コントローラーの'update'アクションを呼び出す
  
#   delete 'lists/:id' => 'lists#destroy', as: 'destroy_list'#deleteリクエストがlists/:idというパスに送信された場合'lists'コントローラーの'destroy'アクションを呼び出す
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  
  has_one_attached :image #Listモデルにtitleとbodyに加えて画像を扱うためのimageカラムが追記されたかのように扱うことができます。
  
  
  validates :title, presence: true
  validates :body, presence: true
  validates :image, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController


  #(app/views/lists/new.html.erb)用------------------------------------------
  def new
    # viewへ渡すためのインスタンス変数に空のModelオブジェクトを生成
    @list = List.new #List.new Listモデルの情報をもとに新しくオブジェクトが作成され、Listモデルに存在するtitle・bodyが格納できる

  end

#投稿されたデータを保存して詳細画面に移動-----------------------------------
  def create

    #データを受け取り新規登録するためのインスタンスを作成
    @list = List.new(list_params)
    #データをデータベースに保存するためのsaveメソッド実行
    if @list.save
      # フラッシュメッセージを定義し、詳細画面へリダイレクト
      flash[:notice] = "投稿に成功しました。"
      #詳細画面へのリダイレクト
      redirect_to list_path(@list.id)
    else

      flash.now[:alert] ="投稿に失敗しました。"
      render :new
    end

  end

#一覧画面(app/views/lists/index.html.erb)用のアクション
  def index
    @lists = List.all #List(モデル）.all 全てのレコードをまとめて取得
  end

#詳細画面
  def show
    @list =List.find(params[:id]) #/lists/1    => List.find(params[:id]) => idが1のレコードを取得
  end

#編集画面
  def edit
    @list = List.find(params[:id]) # データ（レコード）を1件取得

  end

  def update
    list =List.find(params[:id]) # データ（レコード）を1件取得
    list.update(list_params)
    redirect_to list_path(list.id)  # 詳細画面(show.hetm.erb)へリダイレクト
  end

  def destroy
    list = List.find(params[:id]) # データ（レコード）を1件取得
    list.destroy # データ（レコード）を削除
    redirect_to '/lists'  # 投稿一覧画面へリダイレクト
  end

# ここから下はこのcontrollerの中でしか呼び出せません
  private
  #ストロングパラメータ
  def list_params
    params.require(:list).permit(:title, :body, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--フォント変更-->
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>

  <body>

    <header>
      <h1 class="headline"> All Lists</h1>
    </header>

    <nav>
      <ul class="nav-list">

        <li class="nav-list-item">
          <%= link_to "Top", top_path %>
        </li>

        <li class="nav-list-item">
          <%= link_to "Lists", lists_path %>
        </li>

        <li class="nav-list-item">
          <%= link_to "New List", new_list_path %>
        </li>

      </ul>
    <main>
      <!--eachメソッドを実行するとキーと対応する値を取り出すことができます。-->
      <!--キーは :notice、値は "投稿に成功しました。"取り出したキーをmessage_type、値をmessageにそれぞれ代入-->
      <% flash.each do |message_type, message| %>
        <div class="flash-message <%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </main>

  </body>
</html>

app/views/lists/edit.html.erb
<h1>編集画面</h1>

<!--< %= form_with model: @list,url: update_list_path(@list.id),method: :patch do |f| %>
resources :listsに伴い下記に変更-->
<%= form_with model: @list do |f| %>

  <h4>タイトル</h4>
  <%= f.text_field :title %>
  
  <h4>本文</h4>
  <%= f.text_area :body %>
  
  <%= f.submit '保存' %>
  
  <% end %>

app/views/lists/index.html.erb
<div class="list-wrap">
  
<% @lists.each do |list| %>
  <div class="list-box">
    
    <% if list.image.attached? %>
      <%= image_tag list.image,size: "200x200" %>
    <% else %>
      <%= image_tag "no_image", size: "200x200" %>
    <% end %>
    
    <div class="list-comment">
      <span class="list-body"><%= list.body %></span>
      <span class="list-title"><%=link_to list.title, list_path(list.id) %></span>
    </div>
    
  </div>
  
<% end %>

</div>

app/views/lists/new.html.erb
<h1>新規投稿</h1>

<!--errorsは、モデルにバリデーションをかけたときに、発生したエラーの内容を確認できるメソッドです。
any? と組み合わせることで、エラーが発生しているかどうかを判定できます。
また、full_messagesと組み合わせることで、エラーの内容を出力できます。 エラー文は配列で保存されているため、eachを使います
。-->
<% if @list.errors.any? %>
  <% @list.errors.count %>件のエラーが発生しました
  <ul>
    <% @list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
 <% end %> 




<%= form_with model: @list, url: '/lists', method: :post do |f| %>

  <h4>タイトル</h4>
  <%= f.text_field :title %>
  
  <h4>本文</h4>
  <%= f.text_area :body %>
  
  <h4>画像</h4>
  
  <%= f.file_field :image , accept: "image/*" %> <!-- accept: "image/*"画像ファイルしか投稿できないようにしています-->
  
  <%= f.submit '投稿' %>
  
<% end %>

app/views/lists/show.html.erb
<h2>タイトル</h2>

<P><%= @list.title %></P>


<h2>本文</h2>

<p><%= @list.body %></p>

<h2>画像</h2>
<!--< % if @list.image.attached? %>
  < %= image_tag @list.image, size: "300x300" %>
< % else %>
  < %= image_tag 'no_image', size: "300x300" %>
< % end %>-->

<%= image_tag @list.image, size: "300x300" %>

<%= link_to "編集", edit_list_path(@list.id) %>

<!--< %= link_to '表示するテキスト', URL, method: :HTTPメソッド %>-->
<%= link_to "削除", list_path(@list.id), method: :delete, "deta-confirm" => "本当に削除しますか？" %>